spring.application.name=eternalbouquet

# Base configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bouquets?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Presi123
logging.level.org.hibernate.persister.entity=ERROR
logging.level.org.springframework.security=DEBUG

